from PyQt5.QtCore import Qt

print(Qt.MiterJoin)
print(Qt.BevelJoin)
print(Qt.RoundJoin)



layer = iface.activeLayer()
#ps = QgsPalLayerSettings()
print("-----------------TEXT-----------------")
print("fieldName", layer.customProperty("labeling/fieldName"))
print("isExpression", layer.customProperty("labeling/isExpression"))
print("fontFamily", layer.customProperty("labeling/fontFamily"))
print("fontSize", layer.customProperty("labeling/fontSize"))
print("fontSize", layer.customProperty("labeling/dataDefined/Size"))
print("shapeSizeUnits", layer.customProperty("labeling/shapeSizeUnits"))
print("textColorR", layer.customProperty("labeling/textColorR"))
print("textColorG", layer.customProperty("labeling/textColorG"))
print("textColorB", layer.customProperty("labeling/textColorB"))
print("textColorA", layer.customProperty("labeling/textColorA"))
print("textTransp", layer.customProperty("labeling/textTransp"))
print("textColor", layer.customProperty("labeling/dataDefined/Color"))
print("-----------------FORMAT-----------------")
print("wrapChar", layer.customProperty("labeling/wrapChar"))
print("multilineAlign", layer.customProperty("labeling/multilineAlign"))
print("-----------------BUFFER-----------------")
print("bufferDraw", layer.customProperty("labeling/bufferDraw"))
print("bufferColorR", layer.customProperty("labeling/bufferColorR"))
print("bufferColorG", layer.customProperty("labeling/bufferColorG"))
print("bufferColorB", layer.customProperty("labeling/bufferColorB"))
print("bufferColorA", layer.customProperty("labeling/bufferColorA"))
print("bufferTransp", layer.customProperty("labeling/bufferTransp"))
print("BufferColor", layer.customProperty("labeling/dataDefined/BufferColor"))
print("bufferSize", layer.customProperty("labeling/bufferSize"))
print("-----------------BACKGROUND-----------------")
print("shapeDraw", layer.customProperty("labeling/shapeDraw"))
print("shapeSizeX", layer.customProperty("labeling/shapeSizeX"))
print("shapeSizeY", layer.customProperty("labeling/shapeSizeY"))
print("shapeSizeUnits", layer.customProperty("labeling/shapeSizeUnits"))
print("shapeOffsetX", layer.customProperty("labeling/shapeOffsetX"))
print("shapeOffsetY", layer.customProperty("labeling/shapeOffsetY"))
print("shapeOffsetUnits", layer.customProperty("labeling/shapeOffsetUnits"))
print("shapeFillColorR", layer.customProperty("labeling/shapeFillColorR"))
print("shapeFillColorG", layer.customProperty("labeling/shapeFillColorG"))
print("shapeFillColorB", layer.customProperty("labeling/shapeFillColorB"))
print("shapeFillColorA", layer.customProperty("labeling/shapeFillColorA"))
print("ShapeFillColor", layer.customProperty("labeling/dataDefined/ShapeFillColor"))
print("shapeBorderColorR", layer.customProperty("labeling/shapeBorderColorR"))
print("shapeBorderColorG", layer.customProperty("labeling/shapeBorderColorG"))
print("shapeBorderColorB", layer.customProperty("labeling/shapeBorderColorB"))
print("shapeBorderColorA", layer.customProperty("labeling/shapeBorderColorA"))
print("ShapeBorderColor", layer.customProperty("labeling/dataDefined/ShapeBorderColor"))
print("shapeBorderWidth", layer.customProperty("labeling/shapeBorderWidth"))
print("ShapeBorderWidth", layer.customProperty("labeling/dataDefined/ShapeBorderWidth"))
print("shapeJoinStyle", layer.customProperty("labeling/shapeJoinStyle"))
print("-----------------SHADOW-----------------")
print("shadowDraw", layer.customProperty("labeling/shadowDraw"))
print("shadowColorR", layer.customProperty("labeling/shadowColorR"))
print("shadowColorG", layer.customProperty("labeling/shadowColorG"))
print("shadowColorB", layer.customProperty("labeling/shadowColorB"))
print("shadowColorA", layer.customProperty("labeling/shadowColorA"))
print("shadowTransparency", layer.customProperty("labeling/shadowTransparency"))
print("ShadowColor", layer.customProperty("labeling/dataDefined/ShadowColor"))
print("shadowOffsetAngle", layer.customProperty("labeling/shadowOffsetAngle"))
print("shadowOffsetDist", layer.customProperty("labeling/shadowOffsetDist"))
print("shadowOffsetUnits", layer.customProperty("labeling/shadowOffsetUnits"))
print("shadowTransparency", layer.customProperty("labeling/shadowTransparency"))
print("-----------------PLACEMENT-----------------")
print("placement", layer.customProperty("labeling/placement"))
print("quadOffset", layer.customProperty("labeling/quadOffset"))
print("angleOffset", layer.customProperty("labeling/angleOffset"))
print("Rotation", layer.customProperty("labeling/dataDefined/Rotation"))
print("maxCurvedCharAngleIn", layer.customProperty("labeling/maxCurvedCharAngleIn"))
print("maxCurvedCharAngleOut", layer.customProperty("labeling/maxCurvedCharAngleOut"))
print("repeatDistance", layer.customProperty("labeling/repeatDistance"))
print("repeatDistanceUnit", layer.customProperty("labeling/repeatDistanceUnit"))
print("xOffset", layer.customProperty("labeling/xOffset"))
print("yOffset", layer.customProperty("labeling/yOffset"))
print("labelOffsetInMapUnits", layer.customProperty("labeling/labelOffsetInMapUnits"))
print("dist", layer.customProperty("labeling/dist"))
print("distInMapUnits", layer.customProperty("labeling/distInMapUnits"))
print("priority", layer.customProperty("labeling/priority"))
print("Priority", layer.customProperty("labeling/dataDefined/Priority"))
print("-----------------RENDERER-----------------")
print("scaleVisibility", layer.customProperty("labeling/scaleVisibility"))
print("scaleMin", layer.customProperty("labeling/scaleMin"))
print("scaleMax", layer.customProperty("labeling/scaleMax"))
print("fontLimitPixelSize", layer.customProperty("labeling/fontLimitPixelSize"))
print("fontMinPixelSize", layer.customProperty("labeling/fontMinPixelSize"))
print("fontMaxPixelSize", layer.customProperty("labeling/fontMaxPixelSize"))
print("minFeatureSize", layer.customProperty("labeling/minFeatureSize"))
print("fitInPolygonOnly", layer.customProperty("labeling/fitInPolygonOnly"))
print("displayAll", layer.customProperty("labeling/displayAll"))
print("fontMaxPixelSize", layer.customProperty("labeling/fontMaxPixelSize"))

#layer.setCustomProperty("labeling/displayAll", False)
iface.mapCanvas().refresh()