# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsmapfileexport_dialog_base.ui'
#
# Created: Mon Sep 24 12:34:42 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtGui, uic

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsMapfileExportDialogBase(object):
    def setupUi(self, QgsMapfileExportDialogBase):
        QgsMapfileExportDialogBase.setObjectName(_fromUtf8("QgsMapfileExportDialogBase"))
        QgsMapfileExportDialogBase.resize(687, 460)
        QgsMapfileExportDialogBase.setMinimumSize(QtCore.QSize(686, 460))
        QgsMapfileExportDialogBase.setMaximumSize(QtCore.QSize(687, 460))
        self.tabWidget = QtGui.QTabWidget(QgsMapfileExportDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(170, 9, 501, 401))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab0 = QtGui.QWidget()
        self.tab0.setObjectName(_fromUtf8("tab0"))
        self.lblMapFilePath = QtGui.QLabel(self.tab0)
        self.lblMapFilePath.setGeometry(QtCore.QRect(10, 10, 361, 20))
        self.lblMapFilePath.setObjectName(_fromUtf8("lblMapFilePath"))
        self.txtMapFilePath = QtGui.QLineEdit(self.tab0)
        self.txtMapFilePath.setGeometry(QtCore.QRect(10, 30, 431, 20))
        self.txtMapFilePath.setText(_fromUtf8(""))
        self.txtMapFilePath.setObjectName(_fromUtf8("txtMapFilePath"))
        self.btnChooseFile = QtGui.QToolButton(self.tab0)
        self.btnChooseFile.setGeometry(QtCore.QRect(450, 30, 25, 19))
        self.btnChooseFile.setObjectName(_fromUtf8("btnChooseFile"))
        self.check_include = QtGui.QCheckBox(self.tab0)
        self.check_include.setGeometry(QtCore.QRect(10, 50, 201, 17))
        self.check_include.setChecked(True)
        self.check_include.setObjectName(_fromUtf8("check_include"))
        self.groupShapePath = QtGui.QGroupBox(self.tab0)
        self.groupShapePath.setEnabled(False)
        self.groupShapePath.setGeometry(QtCore.QRect(10, 80, 471, 81))
        self.groupShapePath.setFlat(False)
        self.groupShapePath.setObjectName(_fromUtf8("groupShapePath"))
        self.label_4 = QtGui.QLabel(self.groupShapePath)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 351, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupShapePath)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 381, 20))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btnShapePath = QtGui.QToolButton(self.groupShapePath)
        self.btnShapePath.setGeometry(QtCore.QRect(440, 30, 25, 19))
        self.btnShapePath.setObjectName(_fromUtf8("btnShapePath"))
        self.txtShapePath = QtGui.QLineEdit(self.groupShapePath)
        self.txtShapePath.setGeometry(QtCore.QRect(10, 30, 421, 20))
        self.txtShapePath.setText(_fromUtf8(""))
        self.txtShapePath.setObjectName(_fromUtf8("txtShapePath"))
        self.groupIconsetPath = QtGui.QGroupBox(self.tab0)
        self.groupIconsetPath.setEnabled(False)
        self.groupIconsetPath.setGeometry(QtCore.QRect(10, 310, 471, 61))
        self.groupIconsetPath.setObjectName(_fromUtf8("groupIconsetPath"))
        self.txtIconsetPath = QtGui.QLineEdit(self.groupIconsetPath)
        self.txtIconsetPath.setGeometry(QtCore.QRect(10, 30, 421, 20))
        self.txtIconsetPath.setText(_fromUtf8(""))
        self.txtIconsetPath.setObjectName(_fromUtf8("txtIconsetPath"))
        self.btnIconsetPath = QtGui.QToolButton(self.groupIconsetPath)
        self.btnIconsetPath.setGeometry(QtCore.QRect(440, 30, 25, 19))
        self.btnIconsetPath.setObjectName(_fromUtf8("btnIconsetPath"))
        self.groupSymbolsetPath = QtGui.QGroupBox(self.tab0)
        self.groupSymbolsetPath.setEnabled(False)
        self.groupSymbolsetPath.setGeometry(QtCore.QRect(10, 170, 471, 61))
        self.groupSymbolsetPath.setObjectName(_fromUtf8("groupSymbolsetPath"))
        self.txtSymbolsetPath = QtGui.QLineEdit(self.groupSymbolsetPath)
        self.txtSymbolsetPath.setGeometry(QtCore.QRect(10, 30, 421, 20))
        self.txtSymbolsetPath.setText(_fromUtf8(""))
        self.txtSymbolsetPath.setObjectName(_fromUtf8("txtSymbolsetPath"))
        self.btnSymbolsetPath = QtGui.QToolButton(self.groupSymbolsetPath)
        self.btnSymbolsetPath.setGeometry(QtCore.QRect(440, 30, 25, 19))
        self.btnSymbolsetPath.setObjectName(_fromUtf8("btnSymbolsetPath"))
        self.groupFontsetPath = QtGui.QGroupBox(self.tab0)
        self.groupFontsetPath.setEnabled(False)
        self.groupFontsetPath.setGeometry(QtCore.QRect(10, 240, 471, 61))
        self.groupFontsetPath.setObjectName(_fromUtf8("groupFontsetPath"))
        self.txtFontsetPath = QtGui.QLineEdit(self.groupFontsetPath)
        self.txtFontsetPath.setGeometry(QtCore.QRect(10, 30, 421, 20))
        self.txtFontsetPath.setText(_fromUtf8(""))
        self.txtFontsetPath.setObjectName(_fromUtf8("txtFontsetPath"))
        self.btnFontsetPath = QtGui.QToolButton(self.groupFontsetPath)
        self.btnFontsetPath.setGeometry(QtCore.QRect(440, 30, 25, 19))
        self.btnFontsetPath.setObjectName(_fromUtf8("btnFontsetPath"))
        self.tabWidget.addTab(self.tab0, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.txt_mapfile_general = QtGui.QPlainTextEdit(self.tab1)
        self.txt_mapfile_general.setGeometry(QtCore.QRect(10, 10, 471, 331))
        self.txt_mapfile_general.setObjectName(_fromUtf8("txt_mapfile_general"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.cb_layers = QtGui.QComboBox(self.tab2)
        self.cb_layers.setGeometry(QtCore.QRect(170, 20, 301, 22))
        self.cb_layers.setObjectName(_fromUtf8("cb_layers"))
        self.label = QtGui.QLabel(self.tab2)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.title_ = QtGui.QLineEdit(self.tab2)
        self.title_.setGeometry(QtCore.QRect(170, 80, 301, 20))
        self.title_.setObjectName(_fromUtf8("title_"))
        self.category_ = QtGui.QLineEdit(self.tab2)
        self.category_.setGeometry(QtCore.QRect(170, 110, 301, 20))
        self.category_.setObjectName(_fromUtf8("category_"))
        self.result_fields = QtGui.QLineEdit(self.tab2)
        self.result_fields.setEnabled(False)
        self.result_fields.setGeometry(QtCore.QRect(30, 240, 441, 20))
        self.result_fields.setObjectName(_fromUtf8("result_fields"))
        self.visible_ = QtGui.QCheckBox(self.tab2)
        self.visible_.setGeometry(QtCore.QRect(20, 50, 70, 17))
        self.visible_.setChecked(True)
        self.visible_.setObjectName(_fromUtf8("visible_"))
        self.querylable_ = QtGui.QGroupBox(self.tab2)
        self.querylable_.setGeometry(QtCore.QRect(20, 150, 461, 56))
        self.querylable_.setCheckable(True)
        self.querylable_.setObjectName(_fromUtf8("querylable_"))
        self.tolerance_ = QgsDoubleSpinBox(self.querylable_)
        self.tolerance_.setGeometry(QtCore.QRect(308, 23, 141, 23))
        self.tolerance_.setDecimals(4)
        self.tolerance_.setSingleStep(0.001)
        self.tolerance_.setProperty("value", 0.001)
        self.tolerance_.setObjectName(_fromUtf8("tolerance_"))
        self.label_7 = QtGui.QLabel(self.querylable_)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tolerance_unit = QtGui.QComboBox(self.querylable_)
        self.tolerance_unit.setGeometry(QtCore.QRect(147, 24, 141, 20))
        self.tolerance_unit.setObjectName(_fromUtf8("tolerance_unit"))
        self.label_8 = QtGui.QLabel(self.tab2)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(30, 220, 151, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.result_headers = QtGui.QLineEdit(self.tab2)
        self.result_headers.setEnabled(False)
        self.result_headers.setGeometry(QtCore.QRect(30, 290, 441, 20))
        self.result_headers.setObjectName(_fromUtf8("result_headers"))
        self.label_9 = QtGui.QLabel(self.tab2)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(30, 270, 161, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.result_hyperlink = QtGui.QLineEdit(self.tab2)
        self.result_hyperlink.setEnabled(False)
        self.result_hyperlink.setGeometry(QtCore.QRect(30, 340, 441, 20))
        self.result_hyperlink.setObjectName(_fromUtf8("result_hyperlink"))
        self.label_10 = QtGui.QLabel(self.tab2)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(30, 320, 161, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.listWidget = QtGui.QListWidget(self.tab3)
        self.listWidget.setGeometry(QtCore.QRect(30, 30, 161, 271))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtGui.QListWidget(self.tab3)
        self.listWidget_2.setGeometry(QtCore.QRect(310, 30, 161, 271))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.pushButton = QtGui.QPushButton(self.tab3)
        self.pushButton.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(QgsMapfileExportDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(-1, -10, 161, 511))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 161, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet(_fromUtf8("color: rgb(227, 227, 227);\n"
"background-color: rgb(76, 76, 76);\n"
"selection-background-color: rgb(207, 207, 207);\n"
"selection-color: rgb(50, 50, 50);\n"
""))
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(34)
        self.tableWidget.verticalHeader().setMinimumSectionSize(34)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.button_box = QtGui.QDialogButtonBox(QgsMapfileExportDialogBase)
        self.button_box.setGeometry(QtCore.QRect(440, 420, 231, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.lblMapFilePath.setBuddy(self.txtMapFilePath)
        self.label_5.setBuddy(QgsMapfileExportDialogBase.txtMapfilePath)

        self.retranslateUi(QgsMapfileExportDialogBase)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), QgsMapfileExportDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), QgsMapfileExportDialogBase.reject)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), self.tabWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(QgsMapfileExportDialogBase)

    def retranslateUi(self, QgsMapfileExportDialogBase):
        QgsMapfileExportDialogBase.setWindowTitle(_translate("QgsMapfileExportDialogBase", "Exportar capa de un archivo Mapfile", None))
        self.lblMapFilePath.setText(_translate("QgsMapfileExportDialogBase", "Archivo mapfile con definición de una o varias capas (*.map, *.lay)", None))
        self.txtMapFilePath.setToolTip(_translate("QgsMapfileExportDialogBase", "Nombre del archivo MAPFILE con definición de al menos un LAYER", None))
        self.btnChooseFile.setText(_translate("QgsMapfileExportDialogBase", "...", None))
        self.check_include.setText(_translate("QgsMapfileExportDialogBase", "Archivo contiene directiva INCLUDE", None))
        self.groupShapePath.setTitle(_translate("QgsMapfileExportDialogBase", "Carpeta que contiene archivos shapefiles, imágenes raster, etc (SHAPEPATH)", None))
        self.label_4.setText(_translate("QgsMapfileExportDialogBase", "(Requerido si las capas tienen configurado DATA con rutas relativas)", None))
        self.btnShapePath.setText(_translate("QgsMapfileExportDialogBase", "...", None))
        self.txtShapePath.setToolTip(_translate("QgsMapfileExportDialogBase", "Nombre de la ruta a la carpeta que se alojan archivos shapefiles, etc. (SHAPEPATH)", None))
        self.groupIconsetPath.setTitle(_translate("QgsMapfileExportDialogBase", "Carpeta que contine iconos, svg, png, etc (ICONSET)", None))
        self.txtIconsetPath.setToolTip(_translate("QgsMapfileExportDialogBase", "Especificar el directorio donde se guardan los iconos (Opcional)", None))
        self.btnIconsetPath.setText(_translate("QgsMapfileExportDialogBase", "...", None))
        self.groupSymbolsetPath.setTitle(_translate("QgsMapfileExportDialogBase", "Ruta al archivo con definición de símbolos (SYMBOLSET)", None))
        self.txtSymbolsetPath.setToolTip(_translate("QgsMapfileExportDialogBase", "Especificar la ruta al archivo SYMBOLSET (No se recomienda que se encuentre dentro del mapfile) (Requerido)", None))
        self.btnSymbolsetPath.setText(_translate("QgsMapfileExportDialogBase", "...", None))
        self.groupFontsetPath.setTitle(_translate("QgsMapfileExportDialogBase", "Ruta al archivo con fuentes (FONTSET)", None))
        self.txtFontsetPath.setToolTip(_translate("QgsMapfileExportDialogBase", "Especificar la ruta al archivo FONTSET (requerido para etiquetas y marcadores por fuentes)", None))
        self.btnFontsetPath.setText(_translate("QgsMapfileExportDialogBase", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("QgsMapfileExportDialogBase", "General", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("QgsMapfileExportDialogBase", "Previsualización General", None))
        self.label.setText(_translate("QgsMapfileExportDialogBase", "Propiedades de la capa:", None))
        self.label_2.setText(_translate("QgsMapfileExportDialogBase", "Título:", None))
        self.label_3.setText(_translate("QgsMapfileExportDialogBase", "Categoría", None))
        self.visible_.setText(_translate("QgsMapfileExportDialogBase", "Visible", None))
        self.querylable_.setTitle(_translate("QgsMapfileExportDialogBase", "Consultable", None))
        self.label_7.setText(_translate("QgsMapfileExportDialogBase", "Tolerancia", None))
        self.label_8.setText(_translate("QgsMapfileExportDialogBase", "Campos a mostrar en consultas", None))
        self.label_9.setText(_translate("QgsMapfileExportDialogBase", "Títulos de los campos a mostrar", None))
        self.label_10.setText(_translate("QgsMapfileExportDialogBase", "Campo con enlace", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("QgsMapfileExportDialogBase", "Capas", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("QgsMapfileExportDialogBase", "New Item", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("QgsMapfileExportDialogBase", ">>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("QgsMapfileExportDialogBase", "Previsualización Capa", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("QgsMapfileExportDialogBase", "0", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("QgsMapfileExportDialogBase", "1", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("QgsMapfileExportDialogBase", "2", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("QgsMapfileExportDialogBase", "3", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QgsMapfileExportDialogBase", "menu", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("QgsMapfileExportDialogBase", "General", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("QgsMapfileExportDialogBase", "Previsualización General", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("QgsMapfileExportDialogBase", "Capas", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("QgsMapfileExportDialogBase", "Previsualización Capa", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

from qgsdoublespinbox import QgsDoubleSpinBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QgsMapfileExportDialogBase = QtGui.QDialog()
    ui = Ui_QgsMapfileExportDialogBase()
    ui.setupUi(QgsMapfileExportDialogBase)
    QgsMapfileExportDialogBase.show()
    sys.exit(app.exec_())

