# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsmapfileimport_dialog_base.ui'
#
# Created: Mon Aug 20 18:01:23 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from qgis.PyQt import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsMapfileImportDialogBase(object):
    def setupUi(self, QgsMapfileImportDialogBase):
        QgsMapfileImportDialogBase.setObjectName(_fromUtf8("QgsMapfileImportDialogBase"))
        QgsMapfileImportDialogBase.resize(687, 460)
        QgsMapfileImportDialogBase.setMinimumSize(QtCore.QSize(686, 460))
        QgsMapfileImportDialogBase.setMaximumSize(QtCore.QSize(687, 460))
        self.tabWidget = QtGui.QTabWidget(QgsMapfileImportDialogBase)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(170, 9, 501, 401))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab0 = QtGui.QWidget()
        self.tab0.setObjectName(_fromUtf8("tab0"))
        self.label_1 = QtGui.QLabel(self.tab0)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 361, 20))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.txtMapFilePath = QtGui.QLineEdit(self.tab0)
        self.txtMapFilePath.setGeometry(QtCore.QRect(10, 30, 431, 20))
        self.txtMapFilePath.setText(_fromUtf8(""))
        self.txtMapFilePath.setObjectName(_fromUtf8("txtMapFilePath"))
        self.btnMapfilePath = QtGui.QToolButton(self.tab0)
        self.btnMapfilePath.setGeometry(QtCore.QRect(450, 30, 25, 19))
        self.btnMapfilePath.setObjectName(_fromUtf8("btnMapfilePath"))
        self.check_include = QtGui.QCheckBox(self.tab0)
        self.check_include.setGeometry(QtCore.QRect(30, 70, 201, 17))
        self.check_include.setChecked(True)
        self.check_include.setObjectName(_fromUtf8("check_include"))
        self.groupShapePath = QtGui.QGroupBox(self.tab0)
        self.groupShapePath.setEnabled(False)
        self.groupShapePath.setGeometry(QtCore.QRect(0, 140, 491, 81))
        self.groupShapePath.setFlat(False)
        self.groupShapePath.setObjectName(_fromUtf8("groupShapePath"))
        self.label_3 = QtGui.QLabel(self.groupShapePath)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 351, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupShapePath)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 381, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnShapePath = QtGui.QToolButton(self.groupShapePath)
        self.btnShapePath.setGeometry(QtCore.QRect(450, 30, 25, 19))
        self.btnShapePath.setObjectName(_fromUtf8("btnShapePath"))
        self.txtShapePath = QtGui.QLineEdit(self.groupShapePath)
        self.txtShapePath.setGeometry(QtCore.QRect(10, 30, 431, 20))
        self.txtShapePath.setText(_fromUtf8(""))
        self.txtShapePath.setObjectName(_fromUtf8("txtShapePath"))
        self.tabWidget.addTab(self.tab0, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.cb_layers = QtGui.QComboBox(self.tab1)
        self.cb_layers.setGeometry(QtCore.QRect(170, 20, 301, 22))
        self.cb_layers.setObjectName(_fromUtf8("cb_layers"))
        self.label_5 = QtGui.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.title_ = QtGui.QLineEdit(self.tab1)
        self.title_.setGeometry(QtCore.QRect(170, 50, 301, 20))
        self.title_.setObjectName(_fromUtf8("title_"))
        self.txt_mapfile_layer = QtGui.QPlainTextEdit(self.tab1)
        self.txt_mapfile_layer.setGeometry(QtCore.QRect(10, 80, 471, 281))
        self.txt_mapfile_layer.setObjectName(_fromUtf8("txt_mapfile_layer"))
        self.img_layer = QtGui.QLabel(self.tab1)
        self.img_layer.setGeometry(QtCore.QRect(140, 20, 22, 22))
        self.img_layer.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/QgsMapfile/img/mActionDataSourceManager.svg")))
        self.img_layer.setObjectName(_fromUtf8("img_layer"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupSymbolPath = QtGui.QGroupBox(self.tab)
        self.groupSymbolPath.setEnabled(False)
        self.groupSymbolPath.setGeometry(QtCore.QRect(10, 10, 471, 81))
        self.groupSymbolPath.setObjectName(_fromUtf8("groupSymbolPath"))
        self.rbSymbolMap = QtGui.QRadioButton(self.groupSymbolPath)
        self.rbSymbolMap.setGeometry(QtCore.QRect(230, 20, 201, 17))
        self.rbSymbolMap.setObjectName(_fromUtf8("rbSymbolMap"))
        self.rbSymbolset = QtGui.QRadioButton(self.groupSymbolPath)
        self.rbSymbolset.setGeometry(QtCore.QRect(20, 20, 191, 17))
        self.rbSymbolset.setChecked(True)
        self.rbSymbolset.setObjectName(_fromUtf8("rbSymbolset"))
        self.txtSymbolsetPath = QtGui.QLineEdit(self.groupSymbolPath)
        self.txtSymbolsetPath.setGeometry(QtCore.QRect(10, 50, 421, 20))
        self.txtSymbolsetPath.setText(_fromUtf8(""))
        self.txtSymbolsetPath.setObjectName(_fromUtf8("txtSymbolsetPath"))
        self.btnSymbolPath = QtGui.QToolButton(self.groupSymbolPath)
        self.btnSymbolPath.setGeometry(QtCore.QRect(440, 50, 25, 19))
        self.btnSymbolPath.setObjectName(_fromUtf8("btnSymbolPath"))
        self.txt_mapfile_symbols = QtGui.QPlainTextEdit(self.tab)
        self.txt_mapfile_symbols.setGeometry(QtCore.QRect(10, 100, 471, 261))
        self.txt_mapfile_symbols.setObjectName(_fromUtf8("txt_mapfile_symbols"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.txt_mapfile_general = QtGui.QPlainTextEdit(self.tab2)
        self.txt_mapfile_general.setGeometry(QtCore.QRect(10, 10, 471, 351))
        self.txt_mapfile_general.setObjectName(_fromUtf8("txt_mapfile_general"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(QgsMapfileImportDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(-1, -10, 161, 511))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(76, 76, 76);"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 161, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet(_fromUtf8("color: rgb(227, 227, 227);\n"
"background-color: rgb(76, 76, 76);\n"
"selection-background-color: rgb(217, 217, 217);\n"
"selection-color: rgb(50, 50, 50);\n"
""))
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setIconSize(QtCore.QSize(20, 20))
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(10)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/QgsMapfile/img/general.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(10)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/QgsMapfile/img/mActionDataSourceManager.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(10)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/QgsMapfile/img/symbology.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(10)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/QgsMapfile/img/iconCodepadConsole.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.tableWidget.setItem(3, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(39)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.button_box = QtGui.QDialogButtonBox(QgsMapfileImportDialogBase)
        self.button_box.setGeometry(QtCore.QRect(440, 420, 231, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.label_1.setBuddy(self.txtMapFilePath)
        self.label_4.setBuddy(self.txtMapFilePath)

        self.retranslateUi(QgsMapfileImportDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), QgsMapfileImportDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), QgsMapfileImportDialogBase.reject)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), self.tabWidget.setCurrentIndex)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.tableWidget.selectRow)
        QtCore.QMetaObject.connectSlotsByName(QgsMapfileImportDialogBase)
        QgsMapfileImportDialogBase.setTabOrder(self.tableWidget, self.tabWidget)
        QgsMapfileImportDialogBase.setTabOrder(self.tabWidget, self.btnMapfilePath)
        QgsMapfileImportDialogBase.setTabOrder(self.btnMapfilePath, self.txtMapFilePath)
        QgsMapfileImportDialogBase.setTabOrder(self.txtMapFilePath, self.check_include)
        QgsMapfileImportDialogBase.setTabOrder(self.check_include, self.btnShapePath)
        QgsMapfileImportDialogBase.setTabOrder(self.btnShapePath, self.txtShapePath)
        QgsMapfileImportDialogBase.setTabOrder(self.txtShapePath, self.cb_layers)
        QgsMapfileImportDialogBase.setTabOrder(self.cb_layers, self.title_)
        QgsMapfileImportDialogBase.setTabOrder(self.title_, self.txt_mapfile_layer)
        QgsMapfileImportDialogBase.setTabOrder(self.txt_mapfile_layer, self.rbSymbolset)
        QgsMapfileImportDialogBase.setTabOrder(self.rbSymbolset, self.rbSymbolMap)
        QgsMapfileImportDialogBase.setTabOrder(self.rbSymbolMap, self.btnSymbolPath)
        QgsMapfileImportDialogBase.setTabOrder(self.btnSymbolPath, self.txtSymbolsetPath)
        QgsMapfileImportDialogBase.setTabOrder(self.txtSymbolsetPath, self.txt_mapfile_symbols)
        QgsMapfileImportDialogBase.setTabOrder(self.txt_mapfile_symbols, self.txt_mapfile_general)
        QgsMapfileImportDialogBase.setTabOrder(self.txt_mapfile_general, self.button_box)

    def retranslateUi(self, QgsMapfileImportDialogBase):
        QgsMapfileImportDialogBase.setWindowTitle(_translate("QgsMapfileImportDialogBase", "Importar capas Mapserver (Mapfile)", None))
        self.label_1.setText(_translate("QgsMapfileImportDialogBase", "Archivo mapfile con definición de una o varias capas (*.map, *.lay)", None))
        self.txtMapFilePath.setToolTip(_translate("QgsMapfileImportDialogBase", "Nombre de la ruta al archivo MAPFILE con definición de al menos un LAYER", None))
        self.btnMapfilePath.setText(_translate("QgsMapfileImportDialogBase", "...", None))
        self.check_include.setText(_translate("QgsMapfileImportDialogBase", "Archivo contiene directiva INCLUDE", None))
        self.label_3.setText(_translate("QgsMapfileImportDialogBase", "(Requerido si las capas tienen configurado DATA con rutas relativas)", None))
        self.label_4.setText(_translate("QgsMapfileImportDialogBase", "Carpeta que contiene archivos shapefiles, imágenes raster, etc (SHAPEPATH)", None))
        self.btnShapePath.setText(_translate("QgsMapfileImportDialogBase", "...", None))
        self.txtShapePath.setToolTip(_translate("QgsMapfileImportDialogBase", "Nombre de la ruta a la carpeta que se alojan archivos shapefiles, etc. (SHAPEPATH)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("QgsMapfileImportDialogBase", "General", None))
        self.label_5.setText(_translate("QgsMapfileImportDialogBase", "Capas a importar:", None))
        self.label_6.setText(_translate("QgsMapfileImportDialogBase", "Título:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("QgsMapfileImportDialogBase", "Capas", None))
        self.groupSymbolPath.setTitle(_translate("QgsMapfileImportDialogBase", "Definición de símbolos (SYMBOL)", None))
        self.rbSymbolMap.setToolTip(_translate("QgsMapfileImportDialogBase", "(MAP ... SYMBOL ...END END)", None))
        self.rbSymbolMap.setText(_translate("QgsMapfileImportDialogBase", "Dentro del archivo MAPFILE principal", None))
        self.rbSymbolset.setToolTip(_translate("QgsMapfileImportDialogBase", "Recomendado (SYMBOLSET SYMBOL ... END END)", None))
        self.rbSymbolset.setText(_translate("QgsMapfileImportDialogBase", "En archivo externo (SYMBOLSET)", None))
        self.txtSymbolsetPath.setToolTip(_translate("QgsMapfileImportDialogBase", "Especificar la ruta al archivo SYMBOLSET (SYMBOLSETPATH)", None))
        self.btnSymbolPath.setText(_translate("QgsMapfileImportDialogBase", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QgsMapfileImportDialogBase", "Simbología", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("QgsMapfileImportDialogBase", "Previsualización Mapfile", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("QgsMapfileImportDialogBase", "0", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("QgsMapfileImportDialogBase", "1", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("QgsMapfileImportDialogBase", "2", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("QgsMapfileImportDialogBase", "3", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QgsMapfileImportDialogBase", "menu", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("QgsMapfileImportDialogBase", "General", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("QgsMapfileImportDialogBase", "Capas", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("QgsMapfileImportDialogBase", "Simbología", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("QgsMapfileImportDialogBase", "Mapfile", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QgsMapfileImportDialogBase = QtGui.QDialog()
    ui = Ui_QgsMapfileImportDialogBase()
    ui.setupUi(QgsMapfileImportDialogBase)
    QgsMapfileImportDialogBase.show()
    sys.exit(app.exec_())

